-- Primero ejecutar XDisparadores.sql

DELETE FROM Descuentos;
DELETE FROM ProductosEnCategoria;
DELETE FROM Seguimientos;
DELETE FROM DireccionesFavoritas;
DELETE FROM Resenas;
DELETE FROM Respuestas;
DELETE FROM Preguntas;
DELETE FROM ProductosEnLista;
DELETE FROM ProductosEnHistorialVisitas;
DELETE FROM ProductosEnCarrito;
DELETE FROM ListasProductos;
DELETE FROM HistorialesVisitas;
DELETE FROM CarritosCompras;
DELETE FROM Promociones;
DELETE FROM Publicaciones;
DELETE FROM ImagenesDeProductos;
DELETE FROM Imagenes;
DELETE FROM CategoriasProducto;
DELETE FROM Productos;
DELETE FROM Vendedores;
DELETE FROM Tarjetas;
DELETE FROM Direcciones;
DELETE FROM Ubicaciones;
DELETE FROM Usuarios;

ALTER TABLE Usuarios MODIFY idUsuario GENERATED ALWAYS AS IDENTITY RESTART START WITH 1;
ALTER TABLE Ubicaciones MODIFY idUbicacion GENERATED ALWAYS AS IDENTITY RESTART START WITH 1;
ALTER TABLE Direcciones MODIFY idDireccion GENERATED ALWAYS AS IDENTITY RESTART START WITH 1;
ALTER TABLE Tarjetas MODIFY idTarjeta GENERATED ALWAYS AS IDENTITY RESTART START WITH 1;
ALTER TABLE Productos MODIFY idProducto GENERATED ALWAYS AS IDENTITY RESTART START WITH 1;
ALTER TABLE ListasProductos MODIFY idLista GENERATED ALWAYS AS IDENTITY RESTART START WITH 1;
ALTER TABLE Promociones MODIFY idPromocion GENERATED ALWAYS AS IDENTITY RESTART START WITH 1;
ALTER TABLE Publicaciones MODIFY idPublicacion GENERATED ALWAYS AS IDENTITY RESTART START WITH 1;
ALTER TABLE Imagenes MODIFY idImagen GENERATED ALWAYS AS IDENTITY RESTART START WITH 1;
ALTER TABLE ProductosEnHistorialVisitas MODIFY idProductoEnHistorial GENERATED ALWAYS AS IDENTITY RESTART START WITH 1;
ALTER TABLE DireccionesFavoritas MODIFY idDireccionFavorita GENERATED ALWAYS AS IDENTITY RESTART START WITH 1;
ALTER TABLE Seguimientos MODIFY idSeguimiento GENERATED ALWAYS AS IDENTITY RESTART START WITH 1;
