ALTER TABLE Usuarios ADD CONSTRAINT PK_Usuarios PRIMARY KEY (idUsuario);
ALTER TABLE Ubicaciones ADD CONSTRAINT PK_Ubicaciones PRIMARY KEY (idUbicacion);
ALTER TABLE Direcciones ADD CONSTRAINT PK_Direcciones PRIMARY KEY (idDireccion);
ALTER TABLE Tarjetas ADD CONSTRAINT PK_Tarjetas PRIMARY KEY (idTarjeta);
ALTER TABLE Productos ADD CONSTRAINT PK_Productos PRIMARY KEY (idProducto);
ALTER TABLE ListasProductos ADD CONSTRAINT PK_ListasProductos PRIMARY KEY (idLista);
ALTER TABLE ProductosEnHistorialVisitas ADD CONSTRAINT PK_ProdHistorialVisitas PRIMARY KEY (idProductoEnHistorial);
ALTER TABLE Promociones ADD CONSTRAINT PK_Promociones PRIMARY KEY (idPromocion);
ALTER TABLE CategoriasProducto ADD CONSTRAINT PK_CategoriasProducto PRIMARY KEY (nombre);
ALTER TABLE Publicaciones ADD CONSTRAINT PK_Publicaciones PRIMARY KEY (idPublicacion);
ALTER TABLE Imagenes ADD CONSTRAINT PK_Imagenes PRIMARY KEY (idImagen);
ALTER TABLE DireccionesFavoritas ADD CONSTRAINT PK_DireccionesFavoritas PRIMARY KEY (idDireccionFavorita);
ALTER TABLE Seguimientos ADD CONSTRAINT PK_Seguimientos PRIMARY KEY (idSeguimiento);
ALTER TABLE Vendedores ADD CONSTRAINT PK_Vendedores PRIMARY KEY (usuario);
ALTER TABLE CarritosCompras ADD CONSTRAINT PK_CarritosCompras PRIMARY KEY (usuario);
ALTER TABLE HistorialesVisitas ADD CONSTRAINT PK_HistorialesVisitas PRIMARY KEY (usuario);
ALTER TABLE Resenas ADD CONSTRAINT PK_Resenas PRIMARY KEY (publicacion);
ALTER TABLE Respuestas ADD CONSTRAINT PK_Respuestas PRIMARY KEY (publicacion);
ALTER TABLE Preguntas ADD CONSTRAINT PK_Preguntas PRIMARY KEY (publicacion);
ALTER TABLE ProductosEnCarrito ADD CONSTRAINT PK_ProductosEnCarrito PRIMARY KEY (carrito, producto);
ALTER TABLE ProductosEnLista ADD CONSTRAINT PK_ProductosEnLista PRIMARY KEY (lista, producto);
ALTER TABLE Descuentos ADD CONSTRAINT PK_Descuentos PRIMARY KEY (promocion, producto);
ALTER TABLE ProductosEnCategoria ADD CONSTRAINT PK_ProductosEnCategoria PRIMARY KEY (producto, categoria);
ALTER TABLE ImagenesDeProductos ADD CONSTRAINT PK_ImagenDeProducto PRIMARY KEY (producto, imagen);
